language: ruby
rvm:
  - 1.9.3
#  - 1.8.7
#  - 1.9.2

#Prevents installation of plugin's gemfile
gemfile: non-existent-gemfile

before_install:
  # Git repo of the ChiliProject/Redmine
  - export MAIN_REPO="git://github.com/chiliproject/chiliproject.git"
  # Name of your plugin's repo
  - export REPO_NAME=chiliproject_project_group
  # Plugin's name/directory
  - export PLUGIN_NAME=$REPO_NAME
  - export TARGET_DIR="$HOME/chiliproject"
before_script: "./test/ci/before_script.sh"
script: "./test/ci/script.sh"

env:
  - "DB=mysql2 BUNDLE_WITHOUT=rmagick:mysql:postgres:sqlite"
  - "DB=postgres BUNDLE_WITHOUT=rmagick:mysql:mysql2:sqlite"
